### ISSUE TITLE
Fix ble2osc.py to work with Rpi + Bluez

### ISSUE THREAD

**Issue by lazzarello** [lazzarello/freemg#1]
The example `low_level.py` from the upstream Adafruit Bluefruit distribution fails on a Raspberry Pi with raspbian 9 (stretch). Fix that.

Reference the patch in the comments.

**Comment by lazzarello** [comment]
Exception from source

```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "build/bdist.linux-armv7l/egg/Adafruit_BluefruitLE/bluez_dbus/gatt.py", line 102, in characteristic_changed
    on_change(''.join(map(chr, changed_props['Value'])))
  File "ble2oscd.py", line 97, in received
    e = sys.exc_info()[0]
NameError: global name 'sys' is not defined
```
